# This file was generated by GoReleaser. DO NOT EDIT.
cask "ovdb" do
  version "0.30.0"

  on_macos do
    on_arm do
      sha256 "a230868d7ee4509e456bdcc5acba87af78df6c3db471f47ab05188e97ac0dfc7"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c68c3358655e7841aa7e88739ae4fa5aca48ded0984f1dae7949d0433ed9b39"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "48633fe731b0ea7be5dca9a751f611e5f1d91a40109cb7b691e0edc7c14ab567"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "00af7553f04a80719f7c4142a942b80ff9ee603f80972bcbfae9a7a50480c05b"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ovdb"
  desc "ovdb — the OpenVaultDB command-line interface"
  homepage "https://github.com/openvaultdb/openvaultdb-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ovdb"

  # No zap stanza required
end
