# This file was generated by GoReleaser. DO NOT EDIT.
cask "ovdb" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "8740005c874e90412a20df3dc36f25877e5db7da005738fcf5f0ea96c7d56373"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "524a840dfac62bf03e6e9b1df82943ba905df7307a80c8cf02112df692bb839a"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "df4331de907cfa377957ccd5e5178fb82b3f407ec552c9fc9f5259e337bb3f32"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "acbc8190910128726309e5d3e75843bfab62084e03afe4e72171fa3dab8d07ac"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ovdb"
  desc "ovdb — the OpenVaultDB command-line interface"
  homepage "https://github.com/openvaultdb/openvaultdb-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ovdb"

  # No zap stanza required
end
