# This file was generated by GoReleaser. DO NOT EDIT.
cask "ovdb" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "242efb8c683925f78de1dba9b121a328c4bf499bfc52499f7e41189bca768e66"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0f9abcc652139da9fbb12df4963b0c4d2cd5eaedf9068acee78d738a2cbf7ee5"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eb6934a2fe0a6349eedcf0d8f3068543ef46ca80daa1d026823b19074d5fc921"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ed6858cfafd9220155d2eb0c42096ba5a77c24c9cc5652be1feeb03aa7f3b98"
      url "https://github.com/openvaultdb/ovdb/releases/download/v#{version}/ovdb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ovdb"
  desc "ovdb — the OpenVaultDB command-line interface"
  homepage "https://github.com/openvaultdb/openvaultdb-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ovdb"

  # No zap stanza required
end
